CREATE database customer_behaviour;
USE customer_behaviour;

CREATE table customers(
customer_id int PRIMARY KEY,
age  int ,
gender varchar(10),
item_purchased varchar(30),
category varchar(30),
purchase_amount INT,
location varchar(30),
size varchar(5),
color varchar(15),
season varchar(15),
review_rating float,
subscription_status char(3),
shipping_type varchar(30),
discount_applied char(5),
previous_purchases int,
payment_method varchar(30),
frequency_of_purchases varchar(35),
age_group varchar(30),
purchase_frequency_days int);

SELECT * FROM customers LIMIT 20;

-- BUSINESS QUESTIONS

-- 1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customers
group by gender;

-- 2. Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id,purchase_amount
FROM customers
WHERE discount_applied = 'Yes' and purchase_amount >=(SELECT Avg(purchase_amount) FROM customers);

-- 3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average_Product_Rating"
FROM customers
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;

-- 4.Compare the average Purchase Amounts between Standard and Express Shipping?
SELECT shipping_type, AVG(purchase_amount) as "Average_Purchase_Amount"
FROM customers
WHERE shipping_type IN("Standard","Express")
GROUP BY shipping_type;

-- 5. Do subscribed customers spend more?Compare average spend and total revenue between subscribers and non-sunscribers
SELECT subscription_status ,COUNT(customer_id) as "total_customers", ROUND(AVG(purchase_amount),2) as "average spend",SUM(purchase_amount) as "total revenue"
FROM customers
GROUP BY subscription_status;

-- 6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = "Yes" THEN 1 else 0 END)/COUNT(*),2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers in to New,Returning and Loyal based on their total number of
-- previous purchases, and show the count of each segment.
WITH customer_type as (
SELECT customer_id,previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END as customer_segment
FROM customers
)

SELECT customer_segment,count(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- 8. What are the top 3 most purchased products within each category?
WITH item_counts as (
SELECT category,item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customers
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) as "revenue_contribution"
FROM customers
GROUP BY age_group;